language: php
php:
  - 7.1.0
  - 7.1.12
  - 7.1.13
  - 7.1.27
  - 7.2.0
  - 7.2.34
  - 7.3.0
  - 7.3.27
  - 7.4.0
  - 7.4.9
  - 8.0.0
  - 8.0.1
  - 8.0.2

branches:
  only:
    - master
    - develop

before_install:
  - travis_retry composer self-update
  - composer install

before_script:
  - mkdir -p build/logs
  - mkdir -p build/cov

script:
  - ./vendor/bin/phpunit --bootstrap helper/bootstrap.php test
